<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Reloaded.Memory.Buffers</RootNamespace>
    <PackageId>goatcorp.Reloaded.Memory.Buffers</PackageId>
    <AssemblyName>goatcorp.Reloaded.Memory.Buffers</AssemblyName>
    <LangVersion>latest</LangVersion>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageLicenseUrl></PackageLicenseUrl>
    <PackageProjectUrl>https://github.com/Reloaded-Project/Reloaded.Memory.Buffers</PackageProjectUrl>
    <PackageIconUrl></PackageIconUrl>
    <RepositoryUrl>https://github.com/Reloaded-Project/Reloaded.Memory.Buffers</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Description>An implementation of efficient, shared, concurrent and permanent storage of objects in unmanaged memory in static, non-changing locations that last the lifetime of a given process.</Description>
    <Version>2.0.0-goatcorp10</Version>
    <Authors>Sewer56, goatcorp Contributors</Authors>
    <Company></Company>
    <Product>Project Reloaded</Product>
    <Copyright>LGPL V3</Copyright>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Platforms>AnyCPU</Platforms>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageIcon>Icon.png</PackageIcon>
	<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\LICENSE">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
    <None Include="..\Icon.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Reloaded.Memory" Version="7.0.0" />
  </ItemGroup>

</Project>
